rails-marathon/config/routes.rb
Rails.application.routes.draw do
  resources :galleries do
    resources :paintings
  end
end

rails-marathon/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-marathon/app/models/gallery.rb
class Gallery < ApplicationRecord
  validates :name, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, length: { is: 5 }

  has_many :paintings
end

rails-marathon/app/models/painting.rb
class Painting < ApplicationRecord
  validates :title, presence: true
  validates :artist, presence: true

  belongs_to :gallery
end

rails-marathon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails-marathon/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
    @paintings = @gallery.paintings
    @painting = Painting.new
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      flash[:notice] = "Gallery added successfully!"
      redirect_to gallery_path(@gallery)
    else
      errors = ""
      @gallery.errors.full_messages.each do |msg|
        errors += "#{msg}. "
      end
      flash[:notice] = errors
      render "new"
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:name, :city, :state, :zip, :description)
  end
end

rails-marathon/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def new
    @painting = Painting.new
    @gallery = Gallery.find(params[:gallery_id])
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.new(painting_params)
    @painting.gallery = @gallery

    if @painting.save
      flash[:notice] = "Painting added successfully!"
      redirect_to gallery_path(@gallery)
    else
      errors = ""
      @painting.errors.full_messages.each do |msg|
        errors += "#{msg}. "
      end
      flash[:notice] = errors
      render :new
    end
  end

  private

  def painting_params
    params.require(:painting).permit(:artist, :title, :gallery)
  end
end

rails-marathon/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-marathon/app/views/galleries/index.html.erb
<h1>All Galleries</h1>

<ul>
<% @galleries.each do |gallery|%>
  <li><%= link_to gallery.name, gallery_path(gallery) %></li>
<% end%>
</ul>
<br>
<%= link_to "Add a Gallery", new_gallery_path %>

rails-marathon/app/views/galleries/new.html.erb
<h1>New Gallery Form</h1>

<%= form_for (@gallery) do |f| %>
  <div>
    <%= f.label :name, "Name" %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :city, "City" %><br>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state, "State" %><br>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :zip, "Zip" %><br>
    <%= f.text_field :zip %>
  </div>

  <div>
    <%= f.label :description, "Description" %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit "Add Gallery" %><br><br>
    <%= link_to 'All Galleries', galleries_path %>
  </div>
<% end %>

rails-marathon/app/views/galleries/show.html.erb
<h1><%= @gallery.name %></h1>

  <p><strong>City:</strong> <%= @gallery.city %></p>
  <p><strong>State:</strong> <%= @gallery.state %></p>
  <p><strong>ZIP:</strong> <%= @gallery.zip %></p>

  <% if !@gallery.description.blank? %>
    <p><strong>Description:</strong> <%= @gallery.description %></p>
  <% end %>

<h2>Paintings</h2>
  <ul>
  <% @paintings.each do |painting| %>
    <li><%= painting.title %></li>
  <% end %>
</ul>

<p><%= link_to "Add a Painting", new_gallery_painting_path(@gallery) %></p>
<p><%= link_to "All Galleries", galleries_path %></p>

rails-marathon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !notice.blank? %>
  <p id="notice"><%= notice %></p>
<% end %>

<%= yield %>

</body>
</html>

rails-marathon/app/views/paintings/new.html.erb
<h2>New Painting Form</h2>

<%= form_for [@gallery, @painting] do |f| %>
  <div>
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :artist, "Artist" %><br>
    <%= f.text_field :artist %>
  </div>

  <div>
    <%= f.submit "Add Painting" %><br><br>
  </div>
<% end %>